# Generated by Django 3.1.7 on 2021-03-19 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Баланс')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL, verbose_name='Собственник')),
            ],
            options={
                'verbose_name': 'Кошелек',
                'verbose_name_plural': 'Кошельки',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('+', 'Зачисление'), ('-', 'Списание')], max_length=16, verbose_name='Тип транзакции')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Сумма')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата совершения транзакции')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.wallet', verbose_name='Кошелек')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ('-created',),
            },
        ),
    ]
